"""Experimental Astra-plan / Jev-advice boundary; no image or motor interface.

Jev 1.13 accepts text, not pixels, and is unreliable at precise arithmetic.
This module summarizes measured telemetry in code, asks independent typed
questions, and returns a bounded advisory angle increment. A local controller
must enforce joint, contact, balance and trajectory constraints again at use.
HTTP runs in a worker when AsyncJevAdvisor is used; it never steps simulation.

Official contract: https://docs.typesafe.ai/api and /model-jaggedness/jev-1.13
"""
from __future__ import annotations

from concurrent.futures import Future, ThreadPoolExecutor
from dataclasses import asdict, dataclass, replace
import json
import math
import os
import time
from typing import Callable
import urllib.error
import urllib.request

ENDPOINT = "https://api.typesafe.ai/v1/systemone"
MODEL = "jev-1.13.0"
SCHEMA = "doorbench.jev-advisor.v1"
SOURCES = frozenset(("synthetic", "isaac-telemetry", "native-telemetry"))
ACTIONS = ("hold", "increase_angle", "decrease_angle", "reacquire_contact", "request_astra")
PROGRESS_POLICIES = ("require_jev", "local_guard_with_jev_advice")


def _finite(value: float) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value)


@dataclass(frozen=True)
class AstraPlan:
    """A versioned plan supplied by Astra, not generated by the Jev adapter."""

    plan_id: str
    phase: str
    objective: str
    angle_tolerance_rad: float = .02
    maximum_angle_step_rad: float = .01
    contact_threshold_N: float = .15
    excessive_load_N: float = 15.
    maximum_slip_mps: float = .02
    # Explicit opt-in for the press-clock adapter. Older plans retain the
    # original model-required behavior; this never authorizes motor commands.
    progress_policy: str = "require_jev"

    def __post_init__(self):
        if not all(isinstance(v, str) and 0 < len(v) <= 1000 for v in
                   (self.plan_id, self.phase, self.objective)):
            raise ValueError("Plan identity, phase and objective must be nonempty text")
        values = (self.angle_tolerance_rad, self.maximum_angle_step_rad,
                  self.contact_threshold_N, self.excessive_load_N, self.maximum_slip_mps)
        if not all(_finite(v) and v > 0 for v in values):
            raise ValueError("Plan bounds must be finite and positive")
        if self.maximum_angle_step_rad > .05 or self.contact_threshold_N >= self.excessive_load_N:
            raise ValueError("Invalid bounded angle step or contact thresholds")
        if self.progress_policy not in PROGRESS_POLICIES:
            raise ValueError("Explicit supported Jev progress policy required")


@dataclass(frozen=True)
class Telemetry:
    """One measured epoch. Angle error is target minus measured angle, in radians.

    capture_monotonic_s uses the caller's process clock. Never use simulation
    seconds or a wall-clock timestamp for freshness. None means unavailable.
    normal_load_N describes only the named monitored tactile site; it cannot
    establish which object is contacted. Contact pair identity stays in audit.
    """

    episode_id: str
    sample_id: int
    simulation_time_s: float
    capture_monotonic_s: float
    source: str
    normal_load_N: float | None
    angle_error_rad: float | None
    slip_speed_mps: float | None
    joint_margin_rad: float | None
    balance_stable: bool | None
    sensor_valid: bool = True
    contact_scope: str = "monitored_tactile_site"

    def __post_init__(self):
        if not isinstance(self.episode_id, str) or not self.episode_id:
            raise ValueError("An episode identity is required")
        if type(self.sample_id) is not int or self.sample_id < 0 or self.source not in SOURCES:
            raise ValueError("Invalid sample identity or telemetry provenance")
        if not all(_finite(v) and v >= 0 for v in
                   (self.simulation_time_s, self.capture_monotonic_s)):
            raise ValueError("Telemetry clocks must be finite and nonnegative")
        for key in ("normal_load_N", "angle_error_rad", "slip_speed_mps", "joint_margin_rad"):
            value = getattr(self, key)
            if value is not None and (not _finite(value) or (key != "angle_error_rad" and value < 0)):
                raise ValueError("Telemetry must contain finite measurements or None")
        if self.balance_stable is not None and type(self.balance_stable) is not bool:
            raise ValueError("Balance validity must be a bool or None")
        if type(self.sensor_valid) is not bool:
            raise ValueError("Sensor validity must be a bool")
        if self.contact_scope not in ("monitored_tactile_site", "privileged_digit_handle_contact"):
            raise ValueError("Declare the tactile or privileged contact measurement scope")


def summarize_telemetry(sample: Telemetry, plan: AstraPlan) -> dict:
    """Compute all comparisons locally; Jev receives compact English categories."""
    load, angle, slip = sample.normal_load_N, sample.angle_error_rad, sample.slip_speed_mps
    contact = ("unknown" if load is None else "overloaded" if load >= plan.excessive_load_N
               else "loaded" if load >= plan.contact_threshold_N else "unloaded")
    alignment = ("unknown" if angle is None else "within_tolerance" if abs(angle) <= plan.angle_tolerance_rad
                 else "increase_needed" if angle > 0 else "decrease_needed")
    return {
        "sensor_valid": sample.sensor_valid,
        "monitored_site_contact": contact,
        "alignment": alignment,
        "slip": "unknown" if slip is None else "slipping" if slip > plan.maximum_slip_mps else "stable",
        "joint_room": "unknown" if sample.joint_margin_rad is None else
            "limited" if sample.joint_margin_rad < plan.maximum_angle_step_rad else "available",
        "balance": "unknown" if sample.balance_stable is None else "stable" if sample.balance_stable else "unstable",
    }


def build_request(sample: Telemetry, plan: AstraPlan, *, contact_only: bool = False) -> dict:
    request = {
        "model": MODEL,
        "state": {
            "scope": ("Text summaries of a simulator's measured telemetry; no images. Contact is at a monitored tactile site, not verified handle identity."
                      if sample.contact_scope == "monitored_tactile_site" else
                      "Privileged simulator contact-pair audit: normal load between the selected robot digit and the known handle geometry. This is not tactile-only sensing or vision."),
            "plan": {"phase": plan.phase, "objective": plan.objective},
            "observation": summarize_telemetry(sample, plan),
        },
        "questions": {
            "contact": {
                "type": "noul",
                "instructions": "Does `observation.monitored_site_contact` indicate contact load at the monitored tactile site?",
                "criteria": {"true": "The site is loaded or overloaded.", "false": "The site is unloaded. Unknown is insufficient evidence."},
            },
            "angle_action": {
                "type": "choice",
                "instructions": "Which single bounded alignment advice fits `observation` for the current plan? Unknown or invalid evidence requires request_astra; unstable balance, overload or limited joint room requires hold. Otherwise contact loss or slipping requires reacquire_contact. With stable loaded contact, follow alignment.",
                "criteria": {
                    "hold": "Keep angle unchanged: already within tolerance, balance unstable, joint room limited, or load excessive.",
                    "increase_angle": "Increase by the small code-limited step: valid complete evidence, stable loaded contact and balance, joint room available, alignment increase_needed.",
                    "decrease_angle": "Decrease by the small code-limited step: valid complete evidence, stable loaded contact and balance, joint room available, alignment decrease_needed.",
                    "reacquire_contact": "Ask the local skill controller to recover contact: contact unloaded or slipping, otherwise stable balance with joint room available and no overload.",
                    "request_astra": "Request high-level reassessment: invalid sensor or unknown relevant evidence. Do not invent a measurement.",
                },
            },
        },
    }
    if contact_only:
        request["questions"] = {"contact": request["questions"]["contact"]}
    return request


def reference_action(sample: Telemetry, plan: AstraPlan) -> str:
    """Transparent deterministic comparator, not a claimed robotic policy."""
    state = summarize_telemetry(sample, plan)
    if not sample.sensor_valid or "unknown" in state.values():
        return "request_astra"
    if state["balance"] == "unstable" or state["joint_room"] == "limited" or state["monitored_site_contact"] == "overloaded":
        return "hold"
    if state["monitored_site_contact"] == "unloaded" or state["slip"] == "slipping":
        return "reacquire_contact"
    return {"within_tolerance": "hold", "increase_needed": "increase_angle", "decrease_needed": "decrease_angle"}[state["alignment"]]


@dataclass(frozen=True)
class Advice:
    episode_id: str
    sample_id: int
    plan_id: str
    capture_monotonic_s: float
    received_monotonic_s: float
    accepted: bool
    action: str
    angle_step_rad: float
    reason: str
    proposed_action: str | None = None
    contact_probability: float | None = None
    confidence: float | None = None
    model: str | None = None
    latency_ms: float | None = None
    input_tokens: int | None = None

    def to_dict(self) -> dict:
        return asdict(self)


def _abstain(sample: Telemetry, plan: AstraPlan, now_s: float, reason: str) -> Advice:
    return Advice(sample.episode_id, sample.sample_id, plan.plan_id, sample.capture_monotonic_s,
                  now_s, False, "request_astra", 0., reason)


class JevClient:
    """Pinned official HTTP endpoint. No retry: a late control reply is discarded.

    Instantiate only when a live experiment is explicitly selected. Credentials
    remain in the Authorization header and are never part of state or receipts.
    """

    def __init__(self, api_key: str | None = None, *, timeout_s: float = 2.):
        self._key = api_key if api_key is not None else os.environ.get("TYPESAFE_API_KEY")
        if not isinstance(self._key, str) or not self._key.strip():
            raise ValueError("TYPESAFE_API_KEY is required for live Jev calls")
        if not _finite(timeout_s) or not 0 < timeout_s <= 30:
            raise ValueError("HTTP timeout must be in (0, 30] seconds")
        self.timeout_s = timeout_s

    def __call__(self, payload: dict) -> dict:
        request = urllib.request.Request(ENDPOINT, data=json.dumps(payload, allow_nan=False).encode("utf-8"),
            headers={"Authorization": "Bearer " + self._key, "Content-Type": "application/json"}, method="POST")
        # Do not follow redirects carrying a credential to a different service.
        class NoRedirect(urllib.request.HTTPRedirectHandler):
            def redirect_request(self, req, fp, code, msg, headers, newurl):
                return None
        with urllib.request.build_opener(NoRedirect).open(request, timeout=self.timeout_s) as response:
            return json.loads(response.read(1_000_001))


class JevAdvisor:
    def __init__(self, transport: Callable[[dict], dict], *, max_age_s: float = .75,
                 minimum_confidence: float = .8, contact_only: bool = False,
                 clock: Callable[[], float] = time.monotonic):
        if not _finite(max_age_s) or max_age_s <= 0:
            raise ValueError("Freshness window must be finite and positive")
        if not _finite(minimum_confidence) or not 0 <= minimum_confidence <= 1:
            raise ValueError("Confidence threshold must be in [0, 1]")
        self.transport, self.clock = transport, clock
        self.max_age_s, self.minimum_confidence = max_age_s, minimum_confidence
        self.contact_only = contact_only

    def evaluate(self, sample: Telemetry, plan: AstraPlan) -> Advice:
        started = self.clock()
        if not 0 <= started - sample.capture_monotonic_s <= self.max_age_s:
            return _abstain(sample, plan, started, "stale_or_future_telemetry")
        if (not sample.sensor_valid or sample.normal_load_N is None or
                (not self.contact_only and "unknown" in summarize_telemetry(sample, plan).values())):
            return _abstain(sample, plan, started, "missing_or_invalid_evidence")
        try:
            response = self.transport(build_request(sample, plan, contact_only=self.contact_only))
        except Exception as exc:
            # Error type is useful; URLs, headers and provider bodies may contain secrets.
            reason = f"provider_http_{exc.code}" if isinstance(exc, urllib.error.HTTPError) else f"provider_error_{type(exc).__name__}"
            received = self.clock()
            return replace(_abstain(sample, plan, received, reason), latency_ms=(received-started)*1000.)
        received = self.clock()
        if self.contact_only:
            try:
                contact = response["answers"]["contact"]
                probability = contact["noul"]
                usage = response.get("usage", {}).get("input_tokens")
                if (response["model"] != MODEL or contact["type"] != "noul" or
                        not _finite(probability) or not 0 <= probability <= 1 or
                        (usage is not None and (type(usage) is not int or usage < 0))):
                    raise ValueError("Invalid contact answer")
            except (KeyError, TypeError, ValueError, AttributeError):
                return _abstain(sample, plan, received, "invalid_provider_response")
            reason = "contact_judgment_only_no_control" if 0 <= received-sample.capture_monotonic_s <= self.max_age_s else "response_expired"
            return replace(_abstain(sample, plan, received, reason), contact_probability=probability,
                           model=MODEL, latency_ms=(received-started)*1000., input_tokens=usage)
        try:
            answers = response["answers"]
            contact, choice = answers["contact"], answers["angle_action"]
            probability, confidence, action = contact["noul"], choice["confidence"], choice["choice"]
            probabilities = choice["probabilities"]
            if (response["model"] != MODEL or contact["type"] != "noul" or choice["type"] != "choice"
                    or action not in ACTIONS or set(probabilities) != set(ACTIONS)
                    or not all(_finite(v) and 0 <= v <= 1 for v in (probability, confidence, *probabilities.values()))
                    or not math.isclose(sum(probabilities.values()), 1., abs_tol=.02)
                    or probabilities[action] < max(probabilities.values())):
                raise ValueError("Invalid typed response")
            usage = response.get("usage", {}).get("input_tokens")
            if usage is not None and (type(usage) is not int or usage < 0):
                raise ValueError("Invalid usage")
        except (KeyError, TypeError, ValueError, AttributeError):
            return _abstain(sample, plan, received, "invalid_provider_response")
        receipt = Advice(sample.episode_id, sample.sample_id, plan.plan_id, sample.capture_monotonic_s,
                         received, False, "request_astra", 0., "low_confidence", action,
                         probability, confidence, MODEL, (received-started)*1000., usage)
        if not 0 <= received - sample.capture_monotonic_s <= self.max_age_s:
            return replace(receipt, reason="response_expired")
        if confidence < self.minimum_confidence or probabilities[action] < self.minimum_confidence:
            return receipt
        if action == "request_astra":
            return replace(receipt, reason="model_abstained")
        # Model output never overrides deterministic contradictory measurement.
        expected = reference_action(sample, plan)
        if action != expected:
            return replace(receipt, reason="measurement_guard_rejected")
        if action in ("increase_angle", "decrease_angle") and probability < .9:
            return replace(receipt, reason="contact_probability_too_low")
        step = 0.
        if action in ("increase_angle", "decrease_angle"):
            step = math.copysign(min(plan.maximum_angle_step_rad, abs(sample.angle_error_rad)), sample.angle_error_rad)
        return replace(receipt, accepted=True, action=action, angle_step_rad=step, reason="accepted_advice")

    def revalidate(self, advice: Advice, latest: Telemetry, plan: AstraPlan) -> Advice:
        """Call immediately before use; local controller remains responsible for motion."""
        now = self.clock()
        reason = None
        if advice.episode_id != latest.episode_id or advice.plan_id != plan.plan_id:
            reason = "episode_or_plan_changed"
        elif latest.sample_id < advice.sample_id:
            reason = "out_of_order_telemetry"
        elif not 0 <= now-advice.capture_monotonic_s <= self.max_age_s or not 0 <= now-latest.capture_monotonic_s <= self.max_age_s:
            reason = "advice_or_latest_telemetry_expired"
        elif not latest.sensor_valid or "unknown" in summarize_telemetry(latest, plan).values():
            reason = "latest_evidence_invalid"
        elif advice.accepted and reference_action(latest, plan) != advice.action:
            reason = "measurements_changed"
        if reason:
            return replace(advice, accepted=False, action="request_astra", angle_step_rad=0., reason=reason)
        if advice.accepted and advice.angle_step_rad:
            step = math.copysign(min(abs(advice.angle_step_rad), abs(latest.angle_error_rad),
                                     plan.maximum_angle_step_rad, latest.joint_margin_rad), latest.angle_error_rad)
            return replace(advice, angle_step_rad=step)
        return advice


class AsyncJevAdvisor:
    """One in-flight query; completed advice is consumed once. Never blocks poll.

    Every submit/poll belongs on the same controller thread. close() cancels queued
    work but an in-flight HTTP request can finish up to its bounded client timeout.
    """

    def __init__(self, advisor: JevAdvisor):
        self.advisor = advisor
        self._pool = ThreadPoolExecutor(max_workers=1, thread_name_prefix="doorbench-jev")
        self._future: Future | None = None
        self._closed = False

    def submit(self, sample: Telemetry, plan: AstraPlan) -> bool:
        if self._closed or self._future is not None:
            return False
        self._future = self._pool.submit(self.advisor.evaluate, sample, plan)
        return True

    def poll(self, latest: Telemetry, plan: AstraPlan) -> Advice | None:
        if self._closed or self._future is None or not self._future.done():
            return None
        future, self._future = self._future, None
        return self.advisor.revalidate(future.result(), latest, plan)

    def close(self):
        self._closed = True
        self._pool.shutdown(wait=False, cancel_futures=True)
