import React, { useState } from "react";
import type { Manifest } from "./types";
import { DATASET, DOCS, Icon, PageIntro, REPOSITORY } from "./SiteUI";

const SETUP = `git clone https://github.com/adamraudonis/DoorBench.git
cd DoorBench
pip install -e ".[all]"
python scripts/generate_dataset.py --out assets --workers 8`;
const EXAMPLE = `from doorbench.benchmark import DoorEnv

env = DoorEnv("assets/doors/db0002_swing_single", tier="full")
env.reset(scenario="open_and_traverse", seed=0)

for _ in range(600):
    env.apply_joint_torque(env.meta["operator_joint"], 3.0)
    env.apply_joint_torque(env.meta["primary_joint"], 30.0)
    env.step()

print(env.labels().to_dict())`;

function CodeBlock({ code, label }: { code: string; label: string }) {
  const [copied, setCopied] = useState(false);
  return <div className="code-block"><div className="code-heading"><span>{label}</span><button onClick={async () => { try { await navigator.clipboard.writeText(code); setCopied(true); window.setTimeout(() => setCopied(false), 2000); } catch { setCopied(false); } }}>{copied ? "Copied" : "Copy code"}</button></div><pre><code>{code}</code></pre></div>;
}

export function About({ manifest }: { manifest: Manifest }) {
  const doors = manifest.doors.filter((d) => !d.error);
  const stats = [[doors.length, "door environments"], [manifest.families.length, "motion families"], [new Set(doors.map((d) => d.operator)).size, "operator types"], [new Set(doors.map((d) => d.lock)).size, "lock types"], [new Set(doors.map((d) => d.leaf.slab)).size, "slab constructions"]];
  return <div className="page-shell about-page">
    <PageIntro eyebrow="Built for open research" title="A door is more than a handle." aside={<a className="button primary" href={DATASET} target="_blank" rel="noreferrer">Get the dataset <Icon name="external" size={16} /></a>}><p>DoorBench brings articulated geometry, physical parameters, and interaction tasks together in one reproducible collection for robotics simulation.</p></PageIntro>
    <div className="about-stats">{stats.map(([n, label]) => <div key={label}><strong>{Number(n).toLocaleString()}</strong><span>{label}</span></div>)}</div>
    <div className="docs-layout"><aside className="docs-nav"><p className="eyebrow">On this page</p>{[["overview", "What’s inside"], ["quickstart", "Start experimenting"], ["evaluation", "The benchmark"], ["methodology", "Scope & provenance"]].map(([id, text]) => <button key={id} onClick={() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" })}>{text}<Icon name="arrow" size={14} /></button>)}<div className="docs-links"><a href={DATASET} target="_blank" rel="noreferrer">Hugging Face <Icon name="external" size={14} /></a><a href={REPOSITORY} target="_blank" rel="noreferrer">Source repository <Icon name="external" size={14} /></a><a href={`${DOCS}/DATASET_FORMAT.md`} target="_blank" rel="noreferrer">Dataset specification <Icon name="external" size={14} /></a></div></aside>
    <div className="docs-body"><section id="overview"><p className="eyebrow">01 / What’s inside</p><h2>Geometry you can interact with.<br />Parameters you can inspect.</h2><p>Explore spring latches, thumbturns, panic bars, keypads, sliding tracks, and closer mechanisms across a wide range of door constructions. Every environment includes a specification, generated geometry, and parameters for mass, friction, damping, and interaction.</p><div className="format-grid">{[["MJCF", "MuJoCo", "Three fidelity tiers for detailed interaction or faster simulation."], ["USD", "Isaac Sim / Isaac Lab", "Scene and articulation exports for NVIDIA simulation workflows."], ["URDF", "Robotics tooling", "Robot-description exports with joint and coupling information."]].map(([format, name, text]) => <div key={format}><span className="format-label">{format}</span><h3>{name}</h3><p>{text}</p></div>)}</div><p className="sub">Simulator capabilities differ. See the <a href={`${DOCS}/INTEGRATION.md`} target="_blank" rel="noreferrer">integration guide</a> for format-specific behavior and limitations.</p><div className="inline-feature"><Icon name="grid" size={24} /><div><h3>A separate appearance layer</h3><p>Blender renders add scanned materials, lighting, and room context to the same door geometry. Saved images show a fixed pose; the interactive viewer controls the simulation model.</p></div></div></section>
    <section id="quickstart"><p className="eyebrow">02 / Start experimenting</p><h2>From the catalogue to your simulator.</h2><p>Download the prepared dataset from <a href={DATASET} target="_blank" rel="noreferrer">Hugging Face</a>, or generate it locally from the source. Open any door in the catalogue to inspect its parameters and download individual files.</p><CodeBlock label="Terminal · install & generate" code={SETUP} /><p>This minimal example applies torque to one door’s operator and primary joint. It illustrates the API; it is not a robot policy or a successful traversal.</p><CodeBlock label="Python · one door, one interaction" code={EXAMPLE} /><div className="docs-callout"><div><strong>Run the Unitree G1 demo in Isaac Sim.</strong><p>Step-by-step setup, a policy adapter, and native results for four selected doors.</p></div><a className="button" href={`${DOCS}/ISAAC_G1_DEMO.md`} target="_blank" rel="noreferrer">Open researcher guide <Icon name="external" size={16} /></a></div><div className="docs-callout"><div><strong>See an interaction in the browser.</strong><p>Play a recorded scripted-hand episode with a kinematic humanoid figure for scale and motion reference.</p></div><a className="button" href="#/door/db0002_swing_single?reference=1">Play reference demo <Icon name="arrow" size={16} /></a></div><p className="sub">The figure is a visualization of the recorded trajectory. It is not a contact-dynamic or balance-controlled humanoid demonstration.</p></section>
    <section id="evaluation"><p>The standard catalogue is the benchmark collection. <a href="#/pets">Standalone pet doors</a> are supplementary downloads, excluded from robot and human evaluation. An ordinary door with a built-in pet flap remains eligible.</p><p className="eyebrow">03 / The benchmark</p><h2>Opening is only part of the task.</h2><p>Scenarios specify an approach, handle targets, a passage plane, a goal, and a time budget. Episode labels track contact, operator actuation, latch and lock release, traversal, closing, damage, forces, and elapsed time.</p><div className="suite-grid"><div><span className="format-label">Core suite</span><h3>Door + robot</h3><p>Open and traverse, close behind, close an open door, unlock and traverse, or recognize a locked door. This is the default suite.</p></div><div><span className="format-label">Human suite</span><h3>Shared passage</h3><p>Hold open for a person, wait for a person, or knock and wait. These opt-in scenarios use a simulated person and are reported separately.</p></div></div><p>A door is solved only when a policy succeeds on every scenario assigned to it in the selected suite, on every evaluation seed. Later seeds perturb physical parameters and the start pose.</p><div className="docs-inline-links"><a className="text-link" href="#/results">Explore baseline results <Icon name="arrow" size={16} /></a><a className="text-link" href={`${DOCS}/BENCHMARK.md`} target="_blank" rel="noreferrer">Evaluation specification <Icon name="external" size={14} /></a></div></section>
    <section id="methodology"><p className="eyebrow">04 / Scope & provenance</p><h2>Inspectable assumptions.<br />Explicit limitations.</h2><p>The physics catalogs draw on material properties, hardware specifications, and engineering references. Mass and inertia derive from slab constructions; hinge and track friction, spring forces, and damage thresholds are modeled parameters.</p><div className="methodology-list"><div><span>01</span><div><h3>Automated QA is a specific set of checks</h3><p>{manifest.n_signed_off.toLocaleString()} of {manifest.n_doors.toLocaleString()} doors passed the generation QA gates in this dataset. A passing result is not a claim of complete physical realism, visual quality, or regulatory certification.</p></div></div><div><span>02</span><div><h3>Approximations are part of the model</h3><p>Some mechanisms and material behaviors are simplified. Force indicators based on published standards are computational estimates, not compliance certifications. Use the review workspace to record your own assessment.</p></div></div><div><span>03</span><div><h3>Results belong to a dataset revision</h3><p>The published baseline scores predate the current geometry repairs and appearance update. Run metadata records the original commit; those scores are historical, not a validation of the latest assets.</p></div></div></div><p>Geometry is procedurally generated. Photoreal appearance uses <a href="https://polyhaven.com/license" target="_blank" rel="noreferrer">Poly Haven CC0 texture scans</a>; the code is distributed under the <a href={`${REPOSITORY}/blob/master/LICENSE`} target="_blank" rel="noreferrer">MIT license</a>. Physics references and formulas are documented in the <a href={`${DOCS}/PHYSICS.md`} target="_blank" rel="noreferrer">physics model</a>.</p><div className="provenance-strip"><span>Dataset v{manifest.version}</span><span>Generated {manifest.generated.slice(0, 10)}</span><a href="#/review">Open the review workspace <Icon name="arrow" size={14} /></a></div></section>
    </div></div>
  </div>;
}
