#!/usr/bin/env bash
# One-command setup of Isaac Sim 5.1 + Isaac Lab 2.3 + DoorBench on a fresh Ubuntu 22.04 / 24.04 GPU box.
#
#   git clone https://github.com/adamraudonis/DoorBench.git && cd DoorBench && bash isaaclab/cloud/setup.sh
#
# What it does (idempotent, ~10-15 min, ~25 GB disk):
#   1. apt: build tools, git-lfs, ffmpeg, libgl
#   2. miniconda -> env `doorbench` with Python 3.11 (Isaac Sim 5.x requires 3.11)
#   3. pip: torch 2.7.0 cu128, isaacsim[all,extscache]==5.1.0 (NVIDIA pip index)
#   4. git clone IsaacLab @ v2.3.0 into $ISAACLAB_DIR and ./isaaclab.sh --install (rsl_rl included)
#   5. pip install -e DoorBench (usd-core, mujoco) and -e DoorBench/isaaclab (the doorbench_isaaclab extension)
#   6. regenerates the DoorBench dataset if assets/ is missing (git clone brings it; ~40 s otherwise)
#   7. accepts the Omniverse EULA (OMNI_KIT_ACCEPT_EULA=YES) and writes isaaclab/cloud/env.sh
#
# Requirements: NVIDIA driver >= 535 (nvidia-smi works), 32 GB RAM, glibc >= 2.35 (Ubuntu 22.04+).
# Env overrides: ISAACLAB_DIR (default $HOME/IsaacLab), ISAACLAB_REF (v2.3.0), ISAACSIM_VERSION (5.1.0), CONDA_DIR.
#
# NOT EXECUTED ON THE AUTHOR'S MACHINE (Apple silicon, no NVIDIA GPU) - follows the official pip installation guide
# https://isaac-sim.github.io/IsaacLab/main/source/setup/installation/pip_installation.html (Sept 2026).
set -euo pipefail

DOORBENCH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ISAACLAB_DIR="${ISAACLAB_DIR:-$HOME/IsaacLab}"
ISAACLAB_REF="${ISAACLAB_REF:-v2.3.0}"
ISAACSIM_VERSION="${ISAACSIM_VERSION:-5.1.0}"
CONDA_DIR="${CONDA_DIR:-$HOME/miniconda3}"
ENV_NAME="${ENV_NAME:-doorbench}"
export OMNI_KIT_ACCEPT_EULA=YES ACCEPT_EULA=Y

log() { echo -e "\n\033[1;32m[doorbench setup] $*\033[0m"; }

if ! command -v nvidia-smi >/dev/null 2>&1; then
  echo "nvidia-smi not found: this script needs a machine with an NVIDIA GPU + driver >= 535" >&2; exit 1
fi
nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv

log "1/7 apt packages"
if command -v apt-get >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  (sudo -n true 2>/dev/null && SUDO=sudo) || SUDO=""
  $SUDO apt-get update -y
  $SUDO apt-get install -y --no-install-recommends build-essential cmake git git-lfs curl ffmpeg libgl1 libglu1-mesa libxrandr2 libxinerama1 libxcursor1 libxi6 libxt6 libsm6 libice6 libegl1 xvfb
fi

log "2/7 miniconda + python 3.11 env '$ENV_NAME'"
if [ ! -x "$CONDA_DIR/bin/conda" ]; then
  curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
  bash /tmp/miniconda.sh -b -p "$CONDA_DIR"
fi
# shellcheck disable=SC1091
source "$CONDA_DIR/etc/profile.d/conda.sh"
conda env list | grep -q "^$ENV_NAME " || conda create -y -n "$ENV_NAME" python=3.11
conda activate "$ENV_NAME"
python -m pip install --upgrade pip

log "3/7 torch 2.7.0 (cu128) + isaacsim[all,extscache]==$ISAACSIM_VERSION"
pip install -U torch==2.7.0 torchvision==0.22.0 --index-url https://download.pytorch.org/whl/cu128
pip install "isaacsim[all,extscache]==$ISAACSIM_VERSION" --extra-index-url https://pypi.nvidia.com

log "4/7 Isaac Lab $ISAACLAB_REF -> $ISAACLAB_DIR"
if [ ! -d "$ISAACLAB_DIR/.git" ]; then
  git clone --depth 1 --branch "$ISAACLAB_REF" https://github.com/isaac-sim/IsaacLab.git "$ISAACLAB_DIR"
fi
pushd "$ISAACLAB_DIR" >/dev/null
./isaaclab.sh --install rsl_rl
popd >/dev/null

log "5/7 DoorBench + doorbench_isaaclab extension"
pip install -e "$DOORBENCH_DIR[usd,mujoco]" imageio imageio-ffmpeg
pip install -e "$DOORBENCH_DIR/isaaclab"

log "6/7 dataset"
if [ ! -f "$DOORBENCH_DIR/assets/manifest.json" ]; then
  (cd "$DOORBENCH_DIR" && python scripts/generate_dataset.py --out assets --workers 8 --no-thumbs)
fi
(cd "$DOORBENCH_DIR" && python scripts/isaaclab/validate_usd_static.py --workers 8 --quiet --out assets/usd_validation.json)

log "7/7 environment file"
cat > "$DOORBENCH_DIR/isaaclab/cloud/env.sh" <<EOF
# generated by setup.sh - source me:  source isaaclab/cloud/env.sh
source "$CONDA_DIR/etc/profile.d/conda.sh"
conda activate $ENV_NAME
export ISAACLAB_DIR="$ISAACLAB_DIR"
export DOORBENCH_DIR="$DOORBENCH_DIR"
export DOORBENCH_ASSETS="$DOORBENCH_DIR/assets"
export OMNI_KIT_ACCEPT_EULA=YES ACCEPT_EULA=Y
export ISAACLAB_PY="$ISAACLAB_DIR/isaaclab.sh -p"
alias ilab="$ISAACLAB_DIR/isaaclab.sh -p"
EOF
log "done.  Next:
  source isaaclab/cloud/env.sh
  bash isaaclab/cloud/validate.sh                         # headless USD import validation (all 1000 doors)
  bash isaaclab/cloud/train.sh --task DoorBench-Open-Hand-v0 --num_envs 1024 --max_iterations 300
  bash isaaclab/cloud/hero.sh                              # docs/media/isaaclab_hero.{png,mp4}
  bash isaaclab/cloud/eval.sh logs/rsl_rl/doorbench_hand/<run>/model_300.pt"
